### ISSUE TITLE
Update/Add READMEs for all packages in the Monorep

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign#241]
All crates in the sovereign monorepo should have READMEs. These READMEs should explain what the crate does, and how it fits into the overall architecture of sovereign (Is the crate part of the core SDK? Is a part of the module system? Or is it just used by the full node implementation?)

- [x] schemadb (Preston) #333
- [x] sovereign-db (Preston) #333
- [x] demo-app (Preston) #321
- [x] sdk 
- [x] first-read-last-write-cache: exists but needs expanding. (Preston)
     The readme should explain that the cache is a utility for the module system. We should also move the cache under sov-modules-impl/helpers. 
- [x] sov-app-template (Blaze) #305 
- [x] sov-modules-macros (Blaze) #306 
- [x] sov-state (Blazej) #308 
- [x] sov-modules-api (Blaze) #304 
- [x] accounts (Blaze)
- [x] bank (Blaze) #302 
- [x] sequencer (Blaze) #303 
- [x] value-setter #301 
- [x] election #301 
- [x] sov-modules-impl/integration-tests #313
